### ISSUE TITLE
Các loại máy

### ISSUE THREAD

**Issue by QuynhNhu02** [QuynhNhu02/L-p-10A12-nh-m-04#1]

**Comment by NgKhoa-10C12** [comment]
Hiii ae , t tìm được kho báu rồi=))

**Comment by NgKhoa-10C12** [comment]
Má khổ quá , lặn sông lội biển để tới được đây

**Comment by QuynhNhu02** [comment]
=)))))))) may quá

**Comment by PhuongHang10A12** [comment]
má hiển linh ròi=))) mò muốn khóc

**Comment by TranAnhDuong2410** [comment]
Uạ cái nhóm nó hiện ở đâu vậ mọi người, mỗi lần t vô nhóm là cứ phải mò lại cái thư outlook :,)))

**Comment by TranAnhDuong2410** [comment]
à chắc do nhóm mình để public :vv

**Comment by HienCaoPhuNhuan** [comment]
@QuynhNhu02 sao thầy ko thấy @trankhue85 hiện hồn vậy

**Comment by QuynhNhu02** [comment]
@HienCaoPhuNhuan bữa bạn vô được rồi nhưng mà nhấn vô phần issue nó lỗi hay sao nên kh hiện á thầy:((( con mới kêu bạn thử lại

**Comment by HienCaoPhuNhuan** [comment]
> @HienCaoPhuNhuan bữa bạn vô được rồi nhưng mà nhấn vô phần issue nó lỗi hay sao nên kh hiện á thầy:((( con mới kêu bạn thử lại

Cũng hơn 6 tiếng đồng hồ rồi â

**Comment by trankhue85** [comment]
dạ con đây thầy

**Comment by QuynhNhu02** [comment]
> > @HienCaoPhuNhuan bữa bạn vô được rồi nhưng mà nhấn vô phần issue nó lỗi hay sao nên kh hiện á thầy:((( con mới kêu bạn thử lại
> 
> Cũng hơn 6 tiếng đồng hồ rồi â

dạ con xin lỗi thầy con vào github trên web trên máy tính giờ con học xong mới mở lên xem

**Comment by NgKhoa-10C12** [comment]
Mình cùng tìm hiểu , làm word rồi từng cá nhân nộp cho thầy đúng hông thầy @HienCaoPhuNhuan

**Comment by HienCaoPhuNhuan** [comment]
> Mình cùng tìm hiểu , làm word rồi từng cá nhân nộp cho thầy đúng hông thầy @HienCaoPhuNhuan 

Ko con, phân công nhiệm vụ tìm hiểu (thể hiện ở các column trong project). Tất cả hoạt động, câu trả lời đều đc liệt kê trong column đó của các cá nhân. Thành viên trong nhóm tổng hợp lại thành 1 bài word hoàn chỉnh theo mẫu (có thể trang trí theo ý thích) rồi lưu trữ trên repository và nộp khi có yêu cầu

**Comment by NgKhoa-10C12** [comment]
Dạ

**Comment by NgKhoa-10C12** [comment]
Các câu hỏi là mình phải tự tìm hả thầy @HienCaoPhuNhuan  , con thấy khó quá sợ nhóm con làm hơi lâu 🥲 ![image](https://user-images.githubusercontent.com/92133753/137720740-e313863b-ad89-4a5b-bee9-388f3fd1431d.png)

**Comment by HienCaoPhuNhuan** [comment]
> Các câu hỏi là mình phải tự tìm hả thầy @HienCaoPhuNhuan  , con thấy khó quá sợ nhóm con làm hơi lâu 🥲 ![image](https://user-images.githubusercontent.com/92133753/137720740-e313863b-ad89-4a5b-bee9-388f3fd1431d.png)
> 

Đúng rồi, mình tự tìm hiểu. Chịu khó gu gồ, liệt kê từ khóa. Mình có tuần này, tuần sau mà

**Comment by QuynhNhu02** [comment]
@HienCaoPhuNhuan thầy ơi nếu search gg mà kh có bài giải chi tiết mình tự trình bày có sao kh v ạ? Tại tự trình bày con sợ sẽ kh được đúng lắm ạ

**Comment by HienCaoPhuNhuan** [comment]
> @HienCaoPhuNhuan thầy ơi nếu search gg mà kh có bài giải chi tiết mình tự trình bày có sao kh v ạ? Tại tự trình bày con sợ sẽ kh được đúng lắm ạ 

Thì thầy có nói mà, con cứ trình bày theo style của con. Miễn là con thấy nó chỉn chu, dễ nhìn, fine
