### ISSUE TITLE
Bài 4: Bài toán và thuật toán

### ISSUE THREAD

**Issue by QuynhNhu02** [QuynhNhu02/L-p-10A12-nh-m-04#2]

**Comment by QuynhNhu02** [comment]
hiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii

**Comment by PhuongHang10A12** [comment]
neww hoạt activities hã?:))

**Comment by TranAnhDuong2410** [comment]
Uả ròi khi nào làm dị ?

**Comment by QuynhNhu02** [comment]
hi mụi ng

**Comment by TranAnhDuong2410** [comment]
hí lô

**Comment by NgKhoa-10C12** [comment]
Hí=))

**Comment by NgKhoa-10C12** [comment]
T gửi bài của t nha

**Comment by NgKhoa-10C12** [comment]
https://1drv.ms/w/s!AiNKitIeV0dhgQcOjO1BOfEvyE1_

**Comment by NgKhoa-10C12** [comment]
Tìm Input và Output của bài toán
•	Input : tập hợp các số thực , a,b,c (a≠0).
•	Output : tập hợp các số thực X thoả mãn ax2 + bx + c = 0.
Ý tưởng về việc giải thuật toán
Tính d = b2 - 4ac.
- Lần lượt xét ba trường hợp cho giá trị d:
+ nếu d < 0 thì kết luận phương trình vô nghiệm ;
+ nếu d = 0 thì kết luận phương trình có một nghiệm x =-b/2a;
+ nếu d > 0 thì kết luận phương trình có hai nghiệm phân biệt là: x = (-b ± √d) / 2a.
Thuật toán
Thuật toán:
Mô tả thuật toán bằng cách liệt kê:
Bước I. Nhập ba số a, b, c;
Bước 2. d ← (b*b - 4*a*c);
Bước 3 : 
Nếu d<0 thì thông báo phương trình vô nghiệm và kết thúc 
Nếu d=0 thì thông báo phương trình có một nghiệm và tính nghiệm x = -b/(2*a), rồi kết thúc

Nếu d>0 thì thông báo phương trình có hai nghiệm phân biệt và tính nghiệm x1= (-b + -√d) / (2*a) và x2 = (-b - √ d ) / (2*a), rồi kết thúc

**Comment by PhuongHang10A12** [comment]
ũa mấy bạn =))) mình sửa lại cái phần mình làm trên gihub sao z

**Comment by TranAnhDuong2410** [comment]
Uạ khi nào bàn vụ Word

**Comment by NgKhoa-10C12** [comment]
Bây giờ luôn đi

**Comment by NgKhoa-10C12** [comment]
Trang trí luôn cho nó pro

**Comment by NgKhoa-10C12** [comment]
Trong world có hình ảnh để trang trí ko m

**Comment by TranAnhDuong2410** [comment]
Down về á m

**Comment by TranAnhDuong2410** [comment]
![image](https://user-images.githubusercontent.com/92033938/139517767-81ce693f-2977-4c1c-9268-10b0baa64482.png)

**Comment by QuynhNhu02** [comment]
nào xong gửi lên đây rồi mọi người cùng trao đổi chỉnh sửa cho hoàn thiện he

**Comment by QuynhNhu02** [comment]
mọi người kiểm tra thử đã hoàn thành phần bài của mình chưa và xem thử đã đúng với yêu cầu htruoc thầy bảo chưa nha

**Comment by QuynhNhu02** [comment]
@NgKhoa-10C12 nếu m kh vào phần projects để làm được thì nói với tụi t để tụi t ghi vào dùm nha

**Comment by PhuongHang10A12** [comment]
đợi t vẽ cái sơ đồ khối r gửi qua cho nha

**Comment by NgKhoa-10C12** [comment]
> @NgKhoa-10C12 nếu m kh vào phần projects để làm được thì nói với tụi t để tụi t ghi vào dùm nha 

Oke để học thêm xong t hoàn thành phần của t luôn

**Comment by TranAnhDuong2410** [comment]
![image](https://user-images.githubusercontent.com/92033938/139526702-78a38147-4824-48fd-9d1e-ed087dd0bd40.png)

**Comment by TranAnhDuong2410** [comment]
ê làm vầy được hong ?

**Comment by PhuongHang10A12** [comment]
xinh gái quá đóa:))

**Comment by trankhue85** [comment]
oke lắm nha cậu Dương

**Comment by NgKhoa-10C12** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/92033938/139526702-78a38147-4824-48fd-9d1e-ed087dd0bd40.png)
> 
> 
> 
> 

Nhìn dễ thương nè

**Comment by NgKhoa-10C12** [comment]
Lấy nó đi m

**Comment by PhuongHang10A12** [comment]
canh lề lại xíu cho đẹp. Với cả mấy chữ câu 1 2 3 4 đồ này nọ á cho nó to to lên

**Comment by TranAnhDuong2410** [comment]
![image](https://user-images.githubusercontent.com/92033938/139527708-18ba2cb9-0571-4899-a72c-8a35b7fd479c.png)

**Comment by TranAnhDuong2410** [comment]
Nhìn ổn hơn chưa mng?

**Comment by QuynhNhu02** [comment]
t thì thích cái bố cục ban đầu hơn á

**Comment by trankhue85** [comment]
bố cục đầu nó đỉnk hơn á

**Comment by QuynhNhu02** [comment]
@NgKhoa-10C12 đc chưa m ưi

**Comment by NgKhoa-10C12** [comment]
> @NgKhoa-10C12 đc chưa m ưi
> 
> 

Hợp lý r á

**Comment by NgKhoa-10C12** [comment]
Tìm Input và Output của bài toán
• Input : tập hợp các số thực , a,b,c (a≠0).
• Output : tập hợp các số thực X thoả mãn ax2 + bx + c = 0.
Ý tưởng về việc giải thuật toán
Tính d = b2 - 4ac.

Lần lượt xét ba trường hợp cho giá trị d:
•Nếu d < 0 thì kết luận phương trình vô nghiệm ;
•Nếu d = 0 thì kết luận phương trình có một nghiệm x =-b/2a;
•Nếu d > 0 thì kết luận phương trình có hai nghiệm phân biệt là: x = (-b ± √d) / 2a.

Thuật toán:
Mô tả thuật toán bằng cách liệt kê:
-Bước I. Nhập ba số a, b, c;
-Bước 2. d ← (bb - 4ac);
-Bước 3 :
•Nếu d<0
=> Thông báo phương trình vô nghiệm và kết thúc
•Nếu d=0 
=> Thông báo phương trình có một nghiệm và tính nghiệm x = -b/2a), rồi kết thúc
•Nếu d>0 
=> Thông báo phương trình có hai nghiệm phân biệt và tính nghiệm 2 nghiệm :  
x1= (-b + -√d) / (2a)
x2 = (-b - √ d ) / (2a), rồi kết thúc

**Comment by NgKhoa-10C12** [comment]
T gửi phần của t , tụi m copy của t vô world giúp t nha tại t tìm rồi mà ko ra phần collum á🥲

**Comment by QuynhNhu02** [comment]
okokk

**Comment by QuynhNhu02** [comment]
thông tin m lấy từ đâu á để t ghi vào @NgKhoa-10C12

**Comment by TranAnhDuong2410** [comment]
![image](https://user-images.githubusercontent.com/92033938/139573792-9b29327c-2fd5-4d4a-ad2b-9d77cb28f288.png)

**Comment by TranAnhDuong2410** [comment]
Cái nào ổn hươn vậy mọi người

**Comment by TranAnhDuong2410** [comment]
có đóng khung hong, chữ có viền hong, màu thì ntn?

**Comment by QuynhNhu02** [comment]
đẹp quá quá đẹpp

**Comment by QuynhNhu02** [comment]
xịn xịn 100 đuỷm

**Comment by QuynhNhu02** [comment]
vậy là xong bài r ha cảm ơn mọi ngừi zì sự chăm chỉ này hihi
